AddonId: DescriptionFixer_b86cf867-0519-49ef-b7b7-386b6a1e2830
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.12.0
    ReleaseDate: 2025-08-11
    PackageUrl: https://github.com/azuravian/playnite-DescriptionFixer/releases/download/v1.0/DescriptionFixer_b86cf867-0519-49ef-b7b7-386b6a1e2830_1_0.pext
    Changelog:
      - Initial Release
  - Version: 1.1
    RequiredApiVersion: 6.12.0
    ReleaseDate: 2025-08-12
    PackageUrl: https://github.com/azuravian/playnite-DescriptionFixer/releases/download/v1.1/DescriptionFixer_b86cf867-0519-49ef-b7b7-386b6a1e2830_1_1.pext
    Changelog:
      - Added support for converting webp images to png.
  - Version: 1.2
    RequiredApiVersion: 6.12.0
    ReleaseDate: 2025-08-18
    PackageUrl: https://github.com/azuravian/playnite-DescriptionFixer/releases/download/v1.2/DescriptionFixer_b86cf867-0519-49ef-b7b7-386b6a1e2830_1_2.pext
    Changelog:
      - Fixed major bug that caused image files to be overwritten when the same frame number was used in multiple images.
      - Moved video parsing to HtmlAgilityPack. 
  - Version: 1.3.1
    RequiredApiVersion: 6.12.0
    ReleaseDate: 2025-08-23
    PackageUrl: https://github.com/azuravian/playnite-DescriptionFixer/releases/download/v1.3.1/DescriptionFixer_b86cf867-0519-49ef-b7b7-386b6a1e2830_1_3_1.pext
    Changelog:
      - Added conversion of animated gifs to static images.
      - Added repair of Emojis that appear as empty boxes (▯) in Playnite.
      - Fixed bug preventing html descriptions from being saved correctly.
  - Version: 1.3.2
    RequiredApiVersion: 6.12.0
    ReleaseDate: 2025-08-23
    PackageUrl: https://github.com/azuravian/playnite-DescriptionFixer/releases/download/v1.3.2/DescriptionFixer_b86cf867-0519-49ef-b7b7-386b6a1e2830_1_3_2.pext
    Changelog:
      - Fixed crash when trying to process games with no images in the description.